version: '1'
services:
  app:
    build: ./my-app
    volumes:
      - ./coverage:/usr/src/app/coverage
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    environment:
      - NODE_ENV=test
    # command: ["npm", "test"]

  redis:
    image: redis
    ports:
      - "6379:6379"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

