version: '1'
services:
  app:
    build: ./my-app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=test
    command: ["npm", "test"]

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

